on: 
  push:
    branches:
    - main
name: deploy Amazon Prod
jobs:
  deploy:
    name: Amazon deploy PROD_RENE
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        known_hosts: 'frank@frank-HP-ProBook-450-G8-Notebook-PC'
    
    - name: Adding Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST_AMAZON_PROD }} >> ~/.ssh/known_hosts
    
    - name: SSH_ Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      env:
        WOELCOME: "localhost"
      with:
        host: ${{ secrets.SERVER_HOST_AMAZON_PROD }}
        port: 22
        username: "ubuntu"
        private_key: ${{ secrets.PRIVATE_KEY }}
        scp_source: ./*
        scp_target: ~/
        before_script: | 
          echo "before"
        after_script: |          
          pip install -r ~/requirements.txt
          
   